const T = ({ pre, name, note, cls }) => (
  <div class={"tree-line" + (cls ? " " + cls : "")}>
    <span class="tree-pre">{pre}</span>
    <span class="tree-name">{name}</span>
    <span class="tree-note">({note})</span>
  </div>
);

const Structure = () => (
  <Section title="Structure">
    <p class="subdesc">
      The workspace contains <code>serve.js</code> and <code>build.js</code> plus the usual Node.js stuff.
      Each website/app lives in its own project folder.
      The structure is partly opinionated, but not too strict.
    </p>
    <div class="tree">
      <T pre="├─" name="tonka.js"        note="CLI entry: tonka serve / tonka build" cls="accent" />
      <T pre="├─" name="build.js"        note="packs project into production index.html" />
      <T pre="├─" name="serve.js"        note="dev server; serves index.html or main.html + injected links" />
      <T pre="├─" name="utils.js"        note="shared helpers for build.js + serve.js" />
      <T pre="├─" name="package.json"    note="npm config + bin for CLI" />
      <T pre="└─" name="<project>/"      note="one of many projects inside workspace" cls="accent" />
      <T pre="   ├─" name="main.html"    note="required entry for dev" cls="accent" />
      <T pre="   ├─" name="main.jsx"     note="optional main file referenced by main.html" />
      <T pre="   ├─" name="index.html"   note="generated by build; often missing in dev" cls="dim" />
      <T pre="   ├─" name="scripts/"     note="all JS/JSX source files" />
      <T pre="   │  ├─" name="**/*.js"   note=".js loaded first" cls="dim" />
      <T pre="   │  └─" name="**/*.jsx"  note=".jsx loaded second" cls="dim" />
      <T pre="   ├─" name="styles/"      note="all CSS/SCSS styles" />
      <T pre="   │  ├─" name="**/*.css"  note="stylesheets" cls="dim" />
      <T pre="   │  └─" name="**/*.scss" note="planned" cls="dim" />
      <T pre="   ├─" name="images/"      note="static assets" cls="dim" />
      <T pre="   ├─" name="fonts/"       note="static assets" cls="dim" />
      <T pre="   ├─" name="assets/"      note="static assets" cls="dim" />
      <T pre="   └─" name="<any>/"       note="videos, data, etc." cls="dim" />
    </div>
  </Section>
);